### ISSUE TITLE
question: how to use udp to just get battery level

### ISSUE THREAD

**Issue by emko** [FrogTheFrog/steam-gyro-for-cemuhook#14]
sorry if dumb question i see that you are using the UDP connection i am wonder is there a easy way to just get battery data i am writing a electron app that uses controller for navigation and i am having a really hard time understanding how you are getting information from ds4windows.

Thanks

**Comment by FrogTheFrog** [comment]
I'm not using ds4windows, I'm getting data directly from controller. You could copy and trim https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/blob/test/src/lib/steam-device/steam-hid-device.ts file to your project to get almost complete support for steam controller  (remove types if you're using JS only and ANYTHING related to bluetooth, because it's not working without custom drivers).
