### ISSUE TITLE
Fusion with CEMU project

### ISSUE THREAD

**Issue by bphd** [FrogTheFrog/steam-gyro-for-cemuhook#5]
Can you please enter in touch with CEMU dev to integrate your projet as an option in CEMU and work with them to improve Steam Controller integration in CEMU please ? So the work of controller/Steam Controller/Steam Gyro. Controller will be common to all CEMU related dev. :)
Because it's difficult to make simply playable CEMU, so for sit on the crouch, playing on the TV, with a Steam Controller, connected to a Steam Link to your PC, running Steam Big Picture mode, who running Z:BOTW in CEMU, you need to be a dev. for do all of that !

What do you think about an option in CEMU who auto. configure Steam Controller (and Gyro too) in one click ? It would be better than go to GitHub to get an app. that nobody know for configure it ONLY for have the Gyro., not a game fully playable, only the gyro., for the rest you need a ton of configuration...

**Comment by FrogTheFrog** [comment]
@pingo-power Unfortunately I already know their answer - no (that's what I would say).

Motion sensor is not part of a standard input (xinput or dinput). Even a Dolphin dev stated that until it becomes a part of a standard, they won't officially support other motion controllers. The main reason is that supporting different controllers requires to actually own said controller in order to test it and write a code for it. If one controller suddenly becomes supported, community will want others to become supported too. It would soon become a pain in the *** to maintain.

Furthermore, this app only work if controller is connected directly to a PC. At the moment it's impossible to get it to work over Steam link. If devs were to implement this, you would soon hear complaints about it not working over Steam link.

Until Steam devs release an open "Steam input" API, this project won't be implemented into CEMU. Sorry.

**Comment by bphd** [comment]
So just make it as easier as possible for user, the best are a full automatic and ready to play installer
